"use client";
// import type { Metadata } from "next";
import { Sniglet } from "next/font/google";
import NavBar from "./components/NavBar";
import "../app/styles/globals.css";
import { usePathname } from "next/navigation";

export const sniglet = Sniglet({
  subsets: ["latin"],
  variable: "--font-sniglet",
  weight: "800",
});

// export const metadata: Metadata = {
//   title: "JokorHub ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname.startsWith("/auth");

  return (
    <html lang="en">
      <body className={`${sniglet.variable}`}>
        {!isAuthPage && <NavBar />}
        {children}
      </body>
    </html>
  );
}
